export const WEATHER_CONFIG = {
  sunny: {
    bg: "from-amber-100 via-yellow-50 to-orange-100",
    accent: "#F59E0B",
    accentLight: "#FEF3C7",
    accentText: "text-amber-500",
    emoji: "☀️",
    label: "Sunny",
    tagalog: "Maliwanag!",
    messages: [
      "Ang init today 😿 inom tubig ha!",
      "Hot girl summer vibes~ pero mag-sunscreen ka!",
      "Sige labas tayo! Pero uwi bago mag-sunset~",
      "Grabe ang araw! Payong mo, huwag kalimutan 🌞",
    ],
    mood: "happy",
    particle: ["#FDE68A", "#FCD34D", "#FCA5A5"],
  },
  rainy: {
    bg: "from-blue-100 via-slate-50 to-indigo-100",
    accent: "#6366F1",
    accentLight: "#EEF2FF",
    accentText: "text-indigo-500",
    emoji: "🌧️",
    label: "Rainy",
    tagalog: "Maulan!",
    messages: [
      "Umuulan ☔ stay cozy ka~ dito lang tayo",
      "Ayaw lumabas! Netflix + blanket lang tayo~",
      "Mag-dalá ng payong! Basa ka pag hindi 😾",
      "Rainy day = libreng shower sa labas 😹",
    ],
    mood: "cozy",
    particle: ["#BFDBFE", "#A5B4FC", "#C7D2FE"],
  },
  cloudy: {
    bg: "from-slate-100 via-gray-50 to-zinc-100",
    accent: "#8B5CF6",
    accentLight: "#F5F3FF",
    accentText: "text-violet-500",
    emoji: "☁️",
    label: "Cloudy",
    tagalog: "Maulap!",
    messages: [
      "Antok weather ngayon~ sama sama tayo matulog 😴",
      "Malamig-lamig lang~ perfect for coffee!",
      "Hindi maliwanag, hindi madilim~ balance 😌",
      "Pwede na tayo lumabas, pero mag-jacket ka!",
    ],
    mood: "sleepy",
    particle: ["#E9D5FF", "#DDD6FE", "#C4B5FD"],
  },
  windy: {
    bg: "from-teal-100 via-cyan-50 to-sky-100",
    accent: "#0EA5E9",
    accentLight: "#E0F2FE",
    accentText: "text-sky-500",
    emoji: "🌬️",
    label: "Windy",
    tagalog: "Mahangin!",
    messages: [
      "Mahangin! Hawakan mo yung buhok mo~ 💨",
      "Ang hangin! Flying cat mode activated 😹",
      "Breezy vibes~ okay tayo dito!",
      "Huwag mag-umbrella, mabibilog ka 😂",
    ],
    mood: "playful",
    particle: ["#BAE6FD", "#A5F3FC", "#67E8F9"],
  },
};
